apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: homework5-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
   - host: arch.homework
     http:
      paths:
        - path: /otusapp/audintsev($|/)(.*)
          backend:
            serviceName: homework5-service
            servicePort: 8000
